### Fetch all tasks

GET http://localhost:3200/tasks
Content-type: application/json

### Create a new task
POST http://localhost:3200/tasks
Content-type: application/json

{
    "title": "Mololor sit amet",
    "date":  "2021-01-01T12:00:00Z",
    "description": "Genreic description of a task",
    "priority": "normal",
    "status": "todo"
}

### Update A Task
PUT http://localhost:3200/tasks
Content-type: application/json

{
    "id": "9e7b21e7-55af-41a7-ab27-3bdb406dae2e",
    "status": "inProgress"
}